server:
  port: 8082
  servlet:
    context-path: /
spring:
 datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/springbootdubbozk?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 0912
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#        mybatis:
#          type-aliases-package:  domain

##默认密码为空
 redis:
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      jedis:
        pool:
          #连接池最大连接数（使用负值表示没有限制）
          max-active: 100
          # 连接池中的最小空闲连接
          max-idle: 10
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 100000
      # 连接超时时间（毫秒）
      timeout: 5000
      #默认是索引为0的数据库
      database: 0

 mybatis-plus:
          mapper-locations: classpath*:mapper/*Mappering.xml
          type-aliases-package: com.common.domain
